# Generated by Django 3.1 on 2020-08-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestionpedidos', '0004_auto_20200807_1654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulos',
            new_name='Articulo',
        ),
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='pedidos',
            new_name='Pedido',
        ),
    ]
